accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
]


job_portals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('jobs.urls', namespace='jobs')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('home', views.home, name='home'),
    path('joblist/', views.job_list, name='joblist'),
    path('jobs/<int:job_id>/', views.job_detail, name='job_detail'),
    path('companies/', views.company_list, name='companies'),
    path('companydetail/<int:pk>/', views.company_detail, name='companydetail'),
    path('about', views.about, name="about"),
    path('<int:job_id>/apply/', views.apply_job, name='apply'),
    path('job_search/', views.job_search, name='job_search'),
    path('subscribe/', views.newsletter_subscribe, name='newsletter_subscribe'),
]

templates/partials/footer.html
        <!-- Footer-->
        <footer class="bg-dark py-4 mt-auto">
            <div class="container px-5">
              <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto">
                  <div class="small m-0 text-white">© Shabneez Job Portal 2023</div>
                </div>
                <div class="col-auto">
                  <a href="https://www.facebook.com/shab.aurora" target="_blank"  class="text-white me-4"><i class="fab fa-facebook fa-lg"></i></a>
                  <a href="#" target="_blank"  class="text-white me-4"><i class="fab fa-twitter fa-lg"></i></a>
                  <a href="#" target="_blank"  class="text-white me-4"><i class="fab fa-instagram fa-lg"></i></a>
                  <a href="https://www.linkedin.com/in/shabneez-mandarun-4523bb266/" target="_blank" class="text-white me-4"><i class="fab fa-linkedin fa-lg"></i></a>
                </div>
              </div>
            </div>
          </footer>
          
          

templates/partials/head.html
{% load static %}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Job Portal</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'fontawesome/all.min.css' %}">
    <script src="{% static 'fontawesome/js/all.min.js' %}"></script>
</head>

templates/partials/header.html
{% load static %}

<!-- Header-->
    <header class="bg-dark py-5">
    <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center">
            <div class="col-lg-8 col-xl-7 col-xxl-6">
                <div class="my-5 text-center text-xl-start">
                    <h1 class="display-5 fw-bolder text-white mb-2">Find Your Dream Job</h1>
                    <p class="lead fw-normal text-white-50 mb-4">Explore thousands of job listings from top companies and apply today!</p>
                    <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                        <a class="btn btn-primary btn-lg px-4 me-sm-3" href="#features">Get Started</a>
                        <a class="btn btn-outline-light btn-lg px-4" href="#!">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><iframe width="560" height="315" src="https://www.youtube.com/embed/4tXUtMsCyNY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen autoplay></iframe></div>
        </div>
    </div>
</header>

templates/partials/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'jobs:home' %}">Shabneez Job Portal</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 ml-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'jobs:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'jobs:about' %}">About</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'jobs:joblist' %}">Jobs</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'jobs:companies' %}">Companies</a></li>
            
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-light font-weight-bold" href="#">
                      Welcome {{ user.username }}
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link text-warning font-weight-bold" href="{% url 'accounts:logout' %}">
                      Logout
                    </a>
                  </li>
                  
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Register</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav> 
    

templates/partials/welcomevideo.html
{% load static %}
 
 <!-- Welcome video -->
 <section class="welcome-video">
    <div class="embed-responsive embed-responsive-16by9">
      <iframe width="560" height="315" src="https://www.youtube.com/embed/4tXUtMsCyNY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen autoplay></iframe>
    </div>
    <div class="overlay"></div> 
  </section>