job_portals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('jobs.urls', namespace='jobs')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('home', views.home, name='home'),
    path('joblist/', views.job_list, name='joblist'),
    path('jobs/<int:job_id>/', views.job_detail, name='job_detail'),
    path('companies/', views.company_list, name='companies'),
    path('companydetail/<int:pk>/', views.company_detail, name='companydetail'),
    path('about', views.about, name="about"),
    path('<int:job_id>/apply/', views.apply_job, name='apply'),
    path('job_search/', views.job_search, name='job_search'),
    path('subscribe/', views.newsletter_subscribe, name='newsletter_subscribe'),
]

company/models.py
from django.db import models

class Company(models.Model):
    COMPANY_INDUSTRY_CHOICES = (
        ('accounting', 'Accounting'),
        ('advertising', 'Advertising'),
        ('agriculture', 'Agriculture'),
        ('automotive', 'Automotive'),
        ('banking', 'Banking'),
        ('construction', 'Construction'),
        ('education', 'Education'),
        ('entertainment', 'Entertainment'),
        ('finance', 'Finance'),
        ('healthcare', 'Healthcare'),
        ('hospitality', 'Hospitality'),
        ('insurance', 'Insurance'),
        ('manufacturing', 'Manufacturing'),
        ('media', 'Media'),
        ('real-estate', 'Real Estate'),
        ('retail', 'Retail'),
        ('technology', 'Technology'),
        ('telecommunications', 'Telecommunications'),
        ('transportation', 'Transportation'),
    )

    name = models.CharField(max_length=255)
    description = models.TextField()
    logo = models.ImageField(upload_to='company_logos/')
    website = models.URLField()
    location = models.CharField(max_length=255)
    contact_email = models.EmailField()
    contact_phone = models.CharField(max_length=20)
    industry = models.CharField(max_length=20, choices=COMPANY_INDUSTRY_CHOICES)

    def __str__(self):
        return self.name

templates/about.html
{% load static %}
{%include 'partials/nav.html'%}

{%include 'partials/head.html'%}

<!DOCTYPE html>
<html lang="en">
  
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
             <!-- Header-->
             <header class="py-5 bg-dark">
                <div class="container px-5">
                    <div class="row justify-content-center">
                        <div class="col-lg-8 col-xxl-6">
                            <div class="text-center my-5">
                                <h1 class="fw-bolder mb-3 text-white">About Us.</h1>
                                <p class="lead fw-normal text-muted mb-4">Our mission is to connect job seekers with employment opportunities by providing a user-friendly platform that offers access to a wide range of job openings across different industries and locations.</p>
                                <a class="btn btn-primary btn-lg" href="#scroll-target">Read our story</a>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- About section one-->
            <section class="py-5 bg-light" id="scroll-target">
                <div class="container px-5 my-5">
                    <div class="row gx-5 align-items-center">
                        <div class="col-lg-6"><img class="img-fluid rounded mb-5 mb-lg-0" src="{% static 'img/about1.png' %}" /></div>
                        <div class="col-lg-6">
                            <h2 class="fw-bolder">Our founding</h2>
                            <p class="lead fw-normal text-muted mb-0">Our job portal was founded with the mission of connecting talented individuals with their dream jobs, and helping employers find the best candidates to fill their open positions. We understand the challenges that job seekers face in today's competitive job market, as well as the difficulties that companies face in finding the right talent to grow their businesses. That's why we've built a platform that makes it easy for job seekers to discover and apply for job opportunities, and for employers to find and hire top talent. From our founding, we've been committed to delivering exceptional service and support to both job seekers and employers, and we continue to innovate and improve our platform to better serve our users.</p>
                        </div>
                    </div>
                </div>
            </section>
            <!-- About section two-->
            <section class="py-5">
                <div class="container px-5 my-5">
                    <div class="row gx-5 align-items-center">
                        <div class="col-lg-6 order-first order-lg-last"><img class="img-fluid rounded mb-5 mb-lg-0" src="{% static 'img/about2.png' %}" /></div>
                        <div class="col-lg-6">
                            <h2 class="fw-bolder">Growth &amp; beyond</h2>
                            <p class="lead fw-normal text-muted mb-0">At our job portal, we're constantly striving for growth and looking towards the future. We believe that our success is directly tied to the success of our users, and we're committed to helping job seekers and employers achieve their goals. As we continue to grow, we're expanding our offerings and services to better meet the needs of our users. Our focus on innovation and continuous improvement ensures that we're always pushing the boundaries of what's possible in the job market, and we're constantly exploring new ways to make job search and hiring easier and more effective. As we look towards the future, we remain dedicated to providing exceptional service and support to our users, and we're excited to see what new opportunities and possibilities lie ahead.</p>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Team members section-->
            <section class="py-5 bg-light">
                <div class="container px-5 my-5">
                    <div class="text-center">
                        <h2 class="fw-bolder">Our team</h2>
                        <p class="lead fw-normal text-muted mb-5">Dedicated to quality and your success</p>
                    </div>
                    <div class="row gx-5 row-cols-1 row-cols-sm-2 row-cols-xl-4 justify-content-center">
                        <div class="col mb-5 mb-5 mb-xl-0">
                            <div class="text-center">
                                <img class="img-fluid rounded-circle mb-4 px-4" style="height: 50%; width: 100%;" src="{% static 'img/shabneez.jpeg' %}" />
                                <h5 class="fw-bolder">Shabneez</h5>
                                <div class="fst-italic text-muted">Founder &amp; CEO</div>
                            </div>
                        </div>
                        <div class="col mb-5 mb-5 mb-xl-0">
                            <div class="text-center">
                                <img class="img-fluid rounded-circle mb-4 px-4" style="height: 50%; width: 100%;" src="{% static 'img/ceo5.jpeg' %}" />
                                <h5 class="fw-bolder">Vincent</h5>
                                <div class="fst-italic text-muted">CFO</div>
                            </div>
                        </div>
                        <div class="col mb-5 mb-5 mb-xl-0">
                            <div class="text-center">
                                <img class="img-fluid rounded-circle mb-4 px-4" style="height: 50%; width: 100%;" src="{% static 'img/ceo2.jpeg' %}" />
                                <h5 class="fw-bolder">Damien</h5>
                                <div class="fst-italic text-muted">Operations Manager</div>
                            </div>
                        </div>
                        <div class="col mb-5 mb-5 mb-xl-0">
                            <div class="text-center">
                                <img class="img-fluid rounded-circle mb-4 px-4" style="height: 50%; width: 100%;" src="{% static 'img/ceo4.jpeg' %}" />
                                <h5 class="fw-bolder">Anishka</h5>
                                <div class="fst-italic text-muted">CTO</div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
          
            {%include 'partials/footer.html'%}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>

</html>

templates/apply.html
{% extends 'base.html' %}

{% block content %}

<div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Apply Now</h3>
        <br/>
      </div>
      <div class="panel-body">
        <form method="post" action="#" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control" id="name" name="name" required>
          </div>
          <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" id="email" name="email" required>
          </div>
          <div class="form-group">
            <label for="phone">Phone Number:</label>
            <input type="tel" class="form-control" id="phone" name="phone" required>
          </div>
          <br/>
          <div class="form-group">
            <label for="resume">Resume:</label>
            <input type="file" class="form-control-file" id="resume" name="resume" required>
          </div>
          <br/>
          <button type="submit" class="btn btn-primary">Submit Application</button>
        </form>
      </div>
    </div>
  </div>

  {% endblock %}

templates/base.html
{% load static %}
{% include 'partials/nav.html' %}

{% include 'partials/head.html' %}


        {% block content %}
        {% endblock %}

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        {% include 'partials/footer.html' %}
    </body>
</html>

templates/company_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1>Company Detail</h1>
    <hr>
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h2>{{ company.name }}</h2>
        <p><strong>Industry:</strong> {{ company.get_industry_display }}</p>
        <p><strong>Location:</strong> {{ company.location }}</p>
        <p><strong>Website:</strong> <a href="{{ company.website }}" target="_blank">{{ company.website }}</a></p>
        <p><strong>Contact email:</strong> {{ company.contact_email }}</p>
        <p><strong>Contact phone:</strong> {{ company.contact_phone }}</p>
        <hr>
        <p>{{ company.description }}</p>
      </div>
      <div class="col-md-4">
        <img src="{{ company.logo.url }}" alt="{{ company.name }} logo" class="img-fluid">
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/index.html
{% load static %}
{% include 'partials/head.html' %}

    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
          {%include 'partials/nav.html'%}

            <!-- Header-->
            <header class="bg-dark py-5">
                <div class="container px-5">
                    <div class="row gx-5 align-items-center justify-content-center">
                        <div class="col-lg-8 col-xl-7 col-xxl-6">
                            <div class="my-5 text-center text-xl-start">
                              <h1 class="display-5 fw-bolder text-white mb-2">Find Your Dream Job</h1>
                              <p class="lead fw-normal text-white-50 mb-4">Explore thousands of job listings from top companies and apply today!</p>
                                <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                                    <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'jobs:joblist' %}">Get Started</a>
                                    <a class="btn btn-outline-light btn-lg px-4" href="{% url 'jobs:about' %}">Learn More</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><iframe width="560" height="315" src="https://www.youtube.com/embed/4tXUtMsCyNY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen autoplay></iframe></div>
                    </div>
                </div>
            </header>

           <!-- Job Portals section-->
            <section class="py-5" id="job-portals">
                <div class="container px-5 my-5">
                <div class="row gx-5">
                    <div class="col-lg-4 mb-5 mb-lg-0"><h2 class="fw-bolder mb-0">Find Your Dream Job with Job Portals.</h2></div>
                    <div class="col-lg-8">
                    <div class="row gx-5 row-cols-1 row-cols-md-2">
                        <div class="col mb-5 h-100">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-geo-alt"></i></div>
                        <h2 class="h5">Location-Based Search</h2>
                        <p class="mb-0">Search for job openings near your preferred location with our location-based search feature.</p>
                        </div>
                        <div class="col mb-5 h-100">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-briefcase"></i></div>
                        <h2 class="h5">Job Categories</h2>
                        <p class="mb-0">Browse job openings by category and find the one that matches your skills and experience.</p>
                        </div>
                        <div class="col mb-5 mb-md-0 h-100">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-star"></i></div>
                        <h2 class="h5">Saved Jobs</h2>
                        <p class="mb-0">Save the job openings that you're interested in and come back to them later.</p>
                        </div>
                        <div class="col h-100">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-chat-dots"></i></div>
                        <h2 class="h5">Apply Directly</h2>
                        <p class="mb-0">Apply directly to the companies that post their job openings on our platform and get hired faster.</p>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </section>

                    <!-- Testimonial section-->
            <section class="py-5 bg-dark" id="job-testimonials">
              <div class="container px-5 my-5">
                <div class="row gx-5 justify-content-center">
                  <div id="mySlider" class="carousel slide" data-bs-ride="carousel" data-bs-interval="3000">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                      <li data-bs-target="#mySlider" style="background-color: #333; color: #fff;" data-bs-slide-to="0" class="active"></li>
                      <li data-bs-target="#mySlider" style="background-color: #333; color: #fff;" data-bs-slide-to="2"></li>
                      <li data-bs-target="#mySlider" style="background-color: #333; color: #fff;" data-bs-slide-to="1"></li>
                    </ol>
                    <!-- Slides -->
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img src="{% static 'img/job1.jpg' %}" class="d-block w-100" alt="...">
                        <div class="carousel-caption">
                        </div>
                      </div>
                      <div class="carousel-item">
                        <img src="{% static 'img/job2.jpg' %}" class="d-block w-100" alt="...">
                        <div class="carousel-caption">
                        </div>
                      </div>
                      <div class="carousel-item">
                        <img src="{% static 'img/job3.png' %}" class="d-block w-100" alt="...">
                        <div class="carousel-caption">
                        </div>
                      </div>
                    </div>
                    <!-- Controls -->
                    <a class="carousel-control-prev" href="#mySlider" role="button" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#mySlider" role="button" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                    </a>
                  </div>
                </div>
              </div>
            </section>

              
              <!-- Call to action-->
              <section class="py-5 bg-light" id="job-call-to-action">
                  <div class="container px-5 my-5">
                      <div class="row gx-5 justify-content-center">
                          <aside class="bg-primary bg-gradient rounded-3 p-4 p-sm-5" style="height: 200px; width: 100%; ">
                                <div class="d-flex align-items-center justify-content-between flex-column flex-xl-row text-center text-xl-start">
                                    <div class="mb-4 mb-xl-0">
                                        <div class="fs-3 fw-bold text-white">If your desired job was not available we can send you notifications when it becomes availaible.</div>
                                        <div class="text-white-50">Sign up for the latest updates.</div>
                                    </div>
                                    <div class="ms-xl-4">
                                        <form method="POST" action="{% url 'jobs:newsletter_subscribe' %}">
                                            {% csrf_token %}
                                            <div class="input-group mb-2">
                                              <input class="form-control" type="text" name="text" placeholder="Desired Job..." />
                                                <input class="form-control" type="email" name="email" placeholder="Email address..." aria-label="Email address..." aria-describedby="button-newsletter" />
                                                <button class="btn btn-outline-light" id="button-newsletter" type="submit">Sign up</button>
                                            </div>
                                            <div class="small text-white-50">We care about privacy, and will never share your data.</div>
                                        </form>
                                    </div>
                                </div>
                            </aside>
                      </div>
                  </div>
              </section>
              
            
        </main>
        <!-- Footer-->
        {% include 'partials/footer.html' %}
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-DXMehHGjTIi0yP75j3L5pTVWkkx5ZvC5d+fQoaOTlHILbO8tPv60tD47kFjM7w4Q4n1Z7VY/B/N9A38Fj/HRA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/job_details.html
{% extends 'base.html' %}

{% block content %}

     <!-- Header-->
     <header class="py-5 bg-dark">
      <div class="container px-5">
          <div class="row justify-content-center">
              <div class="col-lg-8 col-xxl-6">
                  <div class="text-center my-5">
                      <h1 class="fw-bolder mb-3 text-white">Apply Here</h1>
                      <p class="lead fw-normal text-muted mb-4">Our team will send you an email with feedback as soon as the related company replies.</p>
                      
                  </div>
              </div>
          </div>
      </div>
  </header>

<div class='container' style="margin-top: 30px;">
  <div class="row">
    <div class="col-md-6">
      <h1>{{ job.title }}</h1>
      <p>{{ job.company.name }}, {{ job.location }}</p>
      <p>{{ job.job_type }}, {{ job.job_category }}, {{ job.salary }}</p>
      <p>{{ job.description }}</p>
      <p>{{ job.requirements }}</p>
    </div>
  
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Apply Now</h3>
          <br/>
        </div>
        <div class="panel-body">
          <form method="post" action="{% url 'jobs:apply' job_id=job.id %}" enctype="multipart/form-data"> 
            {% csrf_token %}
            <div class="form-group">
              <label for="name">Name:</label>
              <input type="text" class="form-control" id="name" name="name" required>
            </div>
            <div class="form-group">
              <label for="email">Email:</label>
              <input type="email" class="form-control" id="email" name="email" required>
            </div>
            <div class="form-group">
              <label for="phone">Phone Number:</label>
              <input type="tel" class="form-control" id="phone" name="phone" required>
            </div>
            <br/>
            <div class="form-group">
              <label for="resume">Resume:</label>
              <input type="file" class="form-control-file" id="resume" name="resume" required>
            </div>
            <br>
            <div class="form-group">
              <label for="cover">Cover Letter:</label>
              <input type="file" class="form-control-file" id="cover" name="cover" required>
            </div>
            <div class="form-group">
              <label for="skills">Skills:</label>
              <input type="text" class="form-control" id="skills" name="skills" required>
            </div>
            <br/>
            <button type="submit" class="btn btn-primary">Submit Application</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}


templates/job_listings.html
{% extends "base.html" %}

{% load static %}
{% include 'partials/nav.html' %}
{% include 'partials/header.html' %}

{% block content %}

    <!-- Header-->
    <header class="py-5 bg-dark">
      <div class="container px-5">
          <div class="row justify-content-center">
              <div class="col-lg-8 col-xxl-6">
                  <div class="text-center my-5">
                      <h1 class="fw-bolder mb-3 text-white">Jobs Available Around Mauritius</h1>
                      <p class="lead fw-normal text-muted mb-4">The main industries in Mauritius include financial services, tourism, manufacturing, and information and communication technology (ICT). With a highly skilled and educated workforce, job opportunities in Mauritius can be found in these sectors, as well as in fields such as healthcare, education, and construction.</p>
                      <a class="btn btn-primary btn-lg" href="{% url 'jobs:job_search' %}">Search here</a>
                  </div>
              </div>
          </div>
      </div>
  </header>


  
{% comment %} Job Listings {% endcomment %}
<div class="container" style="margin-top: 30px;">
  <h1>Job List</h1>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Description</th>
        <th>Location</th>
        <th>Job Type</th>
        <th>Job Category</th>
        <th>Salary</th>
        <th>Requirements</th>
        <th>Company</th>
        <th>Date Posted</th>
      </tr>
    </thead>
    <tbody>
      {% for job in jobs %}
      <tr>
        <td>{{ job.id }}</td>
        <td>{{ job.title }}</td>
        <td>{{ job.description }}</td>
        <td>{{ job.location }}</td>
        <td>{{ job.job_type }}</td>
        <td>{{ job.job_category }}</td>
        <td>{{ job.salary }}</td>
        <td>{{ job.requirements }}</td>
        <td>{{ job.company }}</td>
        <td>{{ job.date_posted }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/job_search.html
{% extends 'base.html' %}

{% block content %}

    <!-- Header-->
    <header class="py-5">
        <div class="container px-5">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xxl-6">
                    <div class="text-center my-5">
                        <h1 class="fw-bolder mb-3">Search Your Dream Job</h1>
                      
                    </div>
                </div>
            </div>
        </div>
    </header>

<div class="container" >
    <form method="GET" action="{% url 'jobs:job_search' %}">
      <div class="form-group">
        <label for="title">Job Title:</label>
        <input type="text" id="title" class="form-control" name="title" placeholder="Enter job title">
      </div>
      <div class="form-group">
        <label for="location">Job Location:</label>
        <input type="text" id="location" class="form-control" name="location" placeholder="Enter job location">
      </div>
      <div class="form-group">
        <label for="job_type">Job Type:</label>
        <select id="job_type" name="job_type" class="form-control">
            <option value="">--Select--</option>
          <option value="full-time">Full-time</option>
          <option value="part-time">Part-time</option>
          <option value="contract">Contract</option>
          <option value="freelance">Freelance</option>
          <option value="internship">Internship</option>
        </select>
      </div>
      <div class="form-group">
        <label for="job_category">Job Category:</label>
        <select id="job_category" name="job_category" class="form-control">
            <option value="">--Select--</option>
          <option value="accounting">Accounting</option>
          <option value="administrative">Administrative</option>
          <option value="customer-service">Customer Service</option>
          <option value="engineering">Engineering</option>
          <option value="finance">Finance</option>
          <option value="human-resources">Human Resources</option>
          <option value="information-technology">Information Technology</option>
          <option value="marketing">Marketing</option>
          <option value="sales">Sales</option>
          <option value="healthcare">Health Care</option>
        </select>
      </div>
      <br/>
      <button type="submit" class="btn btn-primary">Search</button>
    </form>
  </div>
  
  <div class="container">

  <h1>Search Results</h1>

  {% if jobs %}
    <p>{{ jobs.count }} jobs found.</p>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Location</th>
          <th>Job Type</th>
          <th>Job Category</th>
          <th>Salary</th>
          <th>Company</th>
          <th>Date Posted</th>
        </tr>
      </thead>
      <tbody>
        {% for job in jobs %}
          <tr>
            <td>{{ job.id }}</td>
            <td>{{ job.title }}</td>
            <td>{{ job.location }}</td>
            <td>{{ job.job_type }}</td>
            <td>{{ job.job_category }}</td>
            <td>{{ job.salary }}</td>
            <td>{{ job.company }}</td>
            <td>{{ job.date_posted|date }}</td>
            <td><a href="{% url 'jobs:job_detail' job.id %}" class="btn btn-primary">Apply</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

  {% else %}
    <p>No jobs found.</p>
  {% endif %}

</div>
</div>

{% endblock %}

templates/thank_you.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-sm mt-5">
                    <div class="card-body">
                        <h1 class="mb-4">Thank You!</h1>
                        <p>Your job application has been received.</p>
                        <p>We will review your application and get back to you soon.</p>
                        <a href="{% url 'jobs:home' %}"class="btn btn-primary mt-4">Back to Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/thankyou_notifications.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-sm mt-5">
                    <div class="card-body">
                        <h1 class="mb-4">Thank You!</h1>
                        <p>Your email has been received.</p>
                        <p>We will send you jobs that match your profile when they come up.</p>
                        <a href="{% url 'jobs:home' %}"class="btn btn-primary mt-4">Back to Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}